[Server]
    Port = ":11081"

[Database]
HostPort = "tcp(127.0.0.1:3306)"
UserPassword = "user:password"
DB = "secKill"
[Database.Conn]
    MaxLifeTime = 600
    MaxIdle = 10
    MaxOpen = 80

[Etcd]
    Endpoints = ["127.0.0.1:12379"]
    EtcdSecActivityKey =  "sec_kill_product"

