[Server]
    Port = ":11081"

[Database]
HostPort = "tcp(172.20.10.20:3306)"
UserPassword = "sendinfo:password"
DB = "secKill"
[Database.Conn]
    MaxLifeTime = 600
    MaxIdle = 10
    MaxOpen = 80

[Etcd]
    Endpoints = ["172.20.10.18:12379"]
    EtcdSecActivityKey =  "sec_kill_product"

